добавлен webpack.config.js и игровая механика
17u5h/game-remember-cards pull request #4
Opened 2022-08-11 08:20 UTC by 17u5h

2022-08-11 21:35 UTC, yadimko requested changes

2022-08-11 21:35 UTC, yadimko commented on gameEngine.js
> +function shuffleDeckAndPushCard() {
В будущем надо поставить ; в конце строк. На проектах линтер будет ругаться)

2022-08-11 21:35 UTC, yadimko commented on package.json
> +{
Вы уже проходили как прописывать скрипты? например для запуска проекта

2022-08-11 21:35 UTC, yadimko commented on style.scss
> +    }
почитай как присваивать это свойство через JS и там уже проще будет

2022-08-12 09:09 UTC, 17u5h commented on gameEngine.js
> +function shuffleDeckAndPushCard() {
Как я не хотел использовать эти точки с запятой, но видимо придется) 
Webstorm не ругается на отсутствие точек с запятой
А про какие проекты идёт речь? В нашей дальнейшей учёбе или в будущих проектах на работе?

2022-08-12 09:11 UTC, 17u5h commented on package.json
> +{
Да, проходили, но я так и не смог запустить( вываливается куча ошибок на стадиях npm run build и npm run start

![image](https://user-images.githubusercontent.com/102058870/184323095-5801bf03-e6fc-42ac-8349-4a98bcbe04f3.png)

Эх, похоже пришло время слазить с windows 7, а так к нему привык(

2022-08-12 09:13 UTC, 17u5h commented on style.scss
> +    }
Я только придумал присвоить стили инлайново. element.style.background = 'url(`./src/img/${suit}-${rank}`)'  Но говорят, что это плохая практика.

2022-08-12 21:09 UTC, yadimko commented on package.json
> +{
какая версия ноды у тебя стоит?

2022-08-12 21:09 UTC, yadimko approved these changes

2022-08-13 01:48 UTC, 17u5h commented on package.json
> +{
Сейчас откатил до 13.14.0
Выпадает пачка ошибок, что-то про HookWebpack. Интернет даёт ответ, что надо ставить году 16+

2022-08-13 01:49 UTC, merged