5th lesson on ts
17u5h/game-remember-cards pull request #5
Opened 2022-08-15 13:52 UTC by 17u5h

вижу косяк функционала в игре: Когда карты угаданы - по ним можно продолжать кликать и они начинают прятаться. Надо будет это пофиксить

2022-08-15 19:26 UTC, mrerberg requested changes

2022-08-15 19:26 UTC, mrerberg commented on renderFinishScreen.ts
> +clearInterval(timerInterval)
Кажется, форматирование съехало

2022-08-15 19:26 UTC, mrerberg commented on renderFinishScreen.ts
> +	container.style.opacity = '0.4'
Лучше стили назначать через класс

2022-08-15 19:26 UTC, mrerberg commented on initialScreen.ts
> +		if (difficultyButtons === null) throw new Error('кнопки выбора сложности не создались')
Ты делаешь throw, а ты ловишь эти ошибки в коде выше? Обрабатываешь?

2022-08-15 19:26 UTC, mrerberg commented on globalVars.ts
> +const cardsCountByDifficulty: {[index: string]: number} = {
index можно четко затипизировать

type Levels = "easy" | "hard";
index: Levels

2022-08-16 05:00 UTC, 17u5h commented on initialScreen.ts
> +		if (difficultyButtons === null) throw new Error('кнопки выбора сложности не создались')
да, по интерпретатору эта строка идёт впереди, но если не сделать еще одну проверку на null внутри функции, тайпскрипт ругается 'TS2531: Object is possibly 'null'.'

```suggestion
		if (difficultyButtons === null || startButton === null) throw new Error('кнопки выбора сложности или кнопка старта не создались')
```

2022-08-16 05:01 UTC, 17u5h commented on renderFinishScreen.ts
> +clearInterval(timerInterval)
поправил во всех файлах

2022-08-16 05:01 UTC, 17u5h commented on renderFinishScreen.ts
> +	container.style.opacity = '0.4'
опять я поторопился и упустил этот момент) исправил)

2022-08-16 05:03 UTC, 17u5h commented on globalVars.ts
> +const cardsCountByDifficulty: {[index: string]: number} = {
сделал, а потом погрел голову чтоб правильно задать тип dataset аттрибуту))
```js
difficulty = cardsCountByDifficulty[datasetDifficulty as keyof typeof cardsCountByDifficulty]
```

2022-08-17 06:27 UTC, mrerberg commented on initialScreen.ts
> +		if (difficultyButtons === null) throw new Error('кнопки выбора сложности не создались')
Я про то, ловишь ли ты эту ошибку try catch блоком где-то? Что произойдет, если выскочит данная ошибка?

2022-08-17 06:30 UTC, mrerberg requested changes

2022-08-17 06:30 UTC, mrerberg commented on renderFinishScreen.ts
> +    const container = document.querySelector('.container') as HTMLElement
Как только ты кастуешь тип с помощью as,компилятор больше не даст тебе предупреждения, что этот элемент может быть null. AS - крайняя мера

2022-08-17 06:30 UTC, mrerberg commented on gameEngine.ts
> +    if (target.classList.contains('guessed')) return
А это что за логика? Ты по классу определяешь, угадал ли пользователь пару?

2022-08-17 06:30 UTC, mrerberg commented on gameEngine.ts
> +            secondClickedCardElement = document.querySelector(`.play-field__card_flipped-${firstClickedCardElement.dataset.suit}-${firstClickedCardElement.dataset.rank}`) as HTMLElement
Лучше вынеси сборку данного селектора в отдельную функцию, чтобы упростить

2022-08-17 06:35 UTC, 17u5h commented on renderFinishScreen.ts
> +    const container = document.querySelector('.container') as HTMLElement
Не знал, спасибо, повешу себе на стенку

2022-08-17 06:36 UTC, 17u5h commented on gameEngine.ts
> +    if (target.classList.contains('guessed')) return
Это чтобы уже угаданные карты нельзя было трогать

2022-08-17 06:44 UTC, 17u5h commented on gameEngine.ts
> +            secondClickedCardElement = document.querySelector(`.play-field__card_flipped-${firstClickedCardElement.dataset.suit}-${firstClickedCardElement.dataset.rank}`) as HTMLElement
ммм... не понятно...
это же надо будет запихуть этот код в функцию, которая будет принимать в себя три параметра и возвращать один?
это точно упрощение?) или я неправильно понимаю?

2022-08-25 09:23 UTC, merged