добавлены unit-тесты для функции createDeck в файле initSetAndSupport.ts
17u5h/game-remember-cards pull request #7
Opened 2022-08-25 10:15 UTC by 17u5h

придумал три юнит теста для этой функции. Наверное это мало. Подскажите если что.

2022-08-26 07:52 UTC, mrerberg requested changes

2022-08-26 07:52 UTC, mrerberg commented on index.test.js
> +    expect(expected).toThrowError('нечетное количество')
Ошибку я бы развернул, описал бы более подробнее

2022-08-26 11:55 UTC, 17u5h commented on index.test.js
> +    expect(expected).toThrowError('нечетное количество')
подправил чтобы другим было понятно что такое "нечетное количество"

2022-08-28 09:25 UTC, mrerberg commented on index.test.js
> +      new Error('нечетное количество карт, игра не получится')
Я бы сформулировал так

Сгенерированно нечетное количество карт. Невозможно начать игру

2022-08-28 12:37 UTC, 17u5h commented on index.test.js
> +      new Error('нечетное количество карт, игра не получится')
Согласен, так более понятно что произошло

2023-03-09 09:50 UTC, merged